const promptData = [
    {
        name: '1. 热门风格 ',
        child: [
            { name: ' 古早风 ', value: 'imgs/rmfg1.png' },
            { name: ' 民国 ', value: 'imgs/rmfg2.png' },
            { name: ' 虚幻引擎 5', value: 'imgs/rmfg3.png' },
            { name: ' 克苏鲁 ', value: 'imgs/rmfg4.png' },
            { name: ' 新艺术 ', value: 'imgs/rmfg5.png' },
            { name: ' 城市摄影 ', value: 'imgs/rmfg6.png' },
            { name: ' 纪实摄影 ', value: 'imgs/rmfg7.png' },
            { name: ' 轻胶感 ', value: 'imgs/rmfg8.png' },
            { name: ' 野生动物摄影 ', value: 'imgs/rmfg9.png' },
            { name: ' 构成主义 ', value: 'imgs/rmfg10.png' },
            { name: ' 抽象主义 ', value: 'imgs/rmfg11.png' },
            { name: ' 电影质感 ', value: 'imgs/rmfg12.png' },
            { name: ' 定格动画 ', value: 'imgs/rmfg13.png' }
        ]
    }, {
        name: '2. 美学 ',
        child: [
            { name: ' 暖色调 ', value: 'imgs/mx1.png' },
            { name: ' 过度曝光 ', value: 'imgs/mx2.png' },
            { name: ' 侧光 ', value: 'imgs/mx3.png' },
            { name: ' 侧逆光 ', value: 'imgs/mx4.png' },
            { name: 'backlighting', value: 'imgs/mx5.png' },
            { name: ' 暖光源 ', value: 'imgs/mx6.png' },
            { name: 'top lighting', value: 'imgs/mx7.png' },
            { name: ' 窗光 ', value: 'imgs/mx8.png' },
            { name: 'soft lighting', value: 'imgs/mx9.png' },
            { name: ' 发丝光 ', value: 'imgs/mx10.png' },
            { name: 'self-illumination', value: 'imgs/mx11.png' },
            { name: ' 火光 ', value: 'imgs/mx12.png' },
            { name: ' 底光 ', value: 'imgs/mx13.png' },
            { name: ' 轮廓光 ', value: 'imgs/mx14.png' },
            { name: 'stage lighting', value: 'imgs/mx15.png' },
            { name: ' 高饱和 ', value: 'imgs/mx16.png' },
            { name: 'high-angle shot', value: 'imgs/mx17.png' },
            { name: ' 丁达尔光 ', value: 'imgs/mx18.png' },
            { name: ' 近景 ', value: 'imgs/mx19.png' },
            { name: ' 中景 ', value: 'imgs/mx20.png' },
            { name: ' 远景 ', value: 'imgs/mx21.png' },
            { name: ' 深景深 ', value: 'imgs/mx22.png' },
            { name: 'full body shot', value: 'imgs/mx23.png' },
            { name: ' 动态模糊 ', value: 'imgs/mx24.png' },
            { name: ' 浅景深 ', value: 'imgs/mx25.png' },
            { name: ' 斜侧视角 ', value: 'imgs/mx26.png' },
            { name: ' 正面光 ', value: 'imgs/mx27.png' },
            { name: 'back view', value: 'imgs/mx28.png' },
            { name: ' 侧面视角 ', value: 'imgs/mx29.png' },
            { name: ' 四分之三侧面 ', value: 'imgs/mx30.png' },
            { name: ' 极端特写 ', value: 'imgs/mx31.png' },
            { name: ' 特写 ', value: 'imgs/mx32.png' },
            { name: ' 鸟瞰 ', value: 'imgs/mx33.png' },
            { name: 'enclosed composition', value: 'imgs/mx34.png' },
            { name: ' 居中构图 ', value: 'imgs/mx35.png' },
            { name: ' 冷光源 ', value: 'imgs/mx36.png' },
            { name: ' 弱光 ', value: 'imgs/mx37.png' },
            { name: ' 冷色调 ', value: 'imgs/mx38.png' },
            { name: ' 低角度视角 ', value: 'imgs/mx39.png' },
            { name: ' 强光 ', value: 'imgs/mx40.png' },
            { name: ' 双性照明 ', value: 'imgs/mx41.png' },
            { name: 'dark-toned', value: 'imgs/mx42.png' },
            { name: ' 低对比度 ', value: 'imgs/mx43.png' },
            { name: ' 亮调 ', value: 'imgs/mx44.png' },
            { name: ' 低饱和 ', value: 'imgs/mx45.png' },
            { name: 'high-contrast', value: 'imgs/mx46.png' },
            { name: ' 硬光 ', value: 'imgs/mx47.png' },
            { name: ' 闪光灯 ', value: 'imgs/mx48.png' }
        ]
    }, {
        name: '3. 摄影 ',
        child: [
            { name: ' 古风摄影 ', value: 'imgs/sy1.png' },
            { name: 'CCD', value: 'imgs/sy2.png' },
            { name: ' 柯达拍摄 ', value: 'imgs/sy3.png' },
            { name: ' 胶片 ', value: 'imgs/sy4.png' },
            { name: ' 人文摄影 ', value: 'imgs/sy5.png' },
            { name: ' 户外摄影 ', value: 'imgs/sy6.png' },
            { name: ' 富士拍摄 ', value: 'imgs/sy7.png' },
            { name: ' 单色摄影 ', value: 'imgs/sy8.png' },
            { name: ' 小清新 ', value: 'imgs/sy9.png' },
            { name: ' 写真摄影 ', value: 'imgs/sy10.png' },
            { name: 'fashion photograph', value: 'imgs/sy11.png' },
            { name: ' 街头摄影 ', value: 'imgs/sy12.png' },
            { name: ' 老照片 ', value: 'imgs/sy13.png' },
            { name: ' 汽车摄影 ', value: 'imgs/sy14.png' },
            { name: ' 夜景摄影 ', value: 'imgs/sy15.png' },
            { name: ' 风景摄影 ', value: 'imgs/sy16.png' }
        ]
    }, {
        name: '4. 潮流 ',
        child: [
            { name: 'Riso', value: 'imgs/cl1.png' },
            { name: ' 皮影 ', value: 'imgs/cl2.png' },
            { name: ' 盲盒 ', value: 'imgs/cl3.png' },
            { name: ' 故障风 ', value: 'imgs/cl4.png' },
            { name: ' 分格漫画 ', value: 'imgs/cl5.png' },
            { name: 'Q 版 ', value: 'imgs/cl6.png' },
            { name: ' 美式复古 ', value: 'imgs/cl7.png' },
            { name: 'BJD', value: 'imgs/cl8.png' },
            { name: ' 千禧 ', value: 'imgs/cl9.png' },
            { name: ' 国风 ', value: 'imgs/cl10.png' },
            { name: ' 魂系游戏 ', value: 'imgs/cl11.png' },
            { name: ' 蒸汽朋克 ', value: 'imgs/cl12.png' },
            { name: ' 波西米亚 ', value: 'imgs/cl13.png' },
            { name: ' 黑暗恐怖 ', value: 'imgs/cl14.png' },
            { name: ' 中世纪 ', value: 'imgs/cl15.png' },
            { name: ' 超级英雄 ', value: 'imgs/cl16.png' },
            { name: ' 蜡笔画 ', value: 'imgs/cl17.png' },
            { name: '90 年代游戏 ', value: 'imgs/cl18.png' },
            { name: ' 港风 ', value: 'imgs/cl19.png' },
            { name: ' 赛博朋克 ', value: 'imgs/cl20.png' }
        ]
    }, {
        name: '5. 艺术 ',
        child: [
            { name: ' 山水画 ', value: 'imgs/ys1.png' },
            { name: ' 皴法 ', value: 'imgs/ys2.png' },
            { name: ' 花鸟画 ', value: 'imgs/ys3.png' },
            { name: ' 仕女图 ', value: 'imgs/ys4.png' },
            { name: ' 绢本画 ', value: 'imgs/ys5.png' },
            { name: ' 工笔风 ', value: 'imgs/ys6.png' },
            { name: ' 浮世绘 ', value: 'imgs/ys7.png' },
            { name: ' 文艺复兴 ', value: 'imgs/ys8.png' },
            { name: ' 巴洛克风格 ', value: 'imgs/ys9.png' },
            { name: ' 新古典主义 ', value: 'imgs/ys10.png' },
            { name: ' 古典主义 ', value: 'imgs/ys11.png' },
            { name: ' 象征主义 ', value: 'imgs/ys12.png' },
            { name: ' 洛可可风格 ', value: 'imgs/ys13.png' },
            { name: ' 浮雕 ', value: 'imgs/ys14.png' },
            { name: ' 大师素描 ', value: 'imgs/ys15.png' },
            { name: ' 速写 ', value: 'imgs/ys16.png' },
            { name: ' 雕塑 ', value: 'imgs/ys17.png' },
            { name: ' 肖像画 ', value: 'imgs/ys18.png' },
            { name: ' 印象派 ', value: 'imgs/ys19.png' },
            { name: ' 拼贴艺术 ', value: 'imgs/ys20.png' },
            { name: ' 大师版画 ', value: 'imgs/ys21.png' },
            { name: ' 超写实主义 ', value: 'imgs/ys22.png' },
            { name: ' 立体主义 ', value: 'imgs/ys23.png' },
            { name: ' 孟菲斯 ', value: 'imgs/ys24.png' }
        ]
    }, {
        name: '6. 材质 ',
        child: [
            { name: 'sisal', value: 'imgs/cz1.png' },
            { name: ' 亚麻绳 ', value: 'imgs/cz2.png' },
            { name: ' 灯芯绒 ', value: 'imgs/cz3.png' },
            { name: ' 亚麻布 ', value: 'imgs/cz4.png' },
            { name: 'wicker', value: 'imgs/cz5.png' },
            { name: ' 竹编 ', value: 'imgs/cz6.png' },
            { name: ' 棉花 ', value: 'imgs/cz7.png' },
            { name: ' 草编 ', value: 'imgs/cz8.png' },
            { name: ' 牛仔布 ', value: 'imgs/cz9.png' },
            { name: ' 沙子 ', value: 'imgs/cz10.png' },
            { name: ' 毛绒 ', value: 'imgs/cz11.png' },
            { name: ' 颗粒纹理 ', value: 'imgs/cz12.png' },
            { name: ' 木头 ', value: 'imgs/cz13.png' },
            { name: ' 植绒 ', value: 'imgs/cz14.png' },
            { name: ' 羽毛 ', value: 'imgs/cz15.png' },
            { name: ' 皮革 ', value: 'imgs/cz16.png' },
            { name: 'velvet', value: 'imgs/cz17.png' },
            { name: ' 火山熔岩 ', value: 'imgs/cz18.png' },
            { name: ' 树脂 ', value: 'imgs/cz19.png' },
            { name: 'gel', value: 'imgs/cz20.png' },
            { name: ' 超轻粘土 ', value: 'imgs/cz21.png' },
            { name: ' 粘土 ', value: 'imgs/cz22.png' },
            { name: ' 泡沫 ', value: 'imgs/cz23.png' },
            { name: 'felt', value: 'imgs/cz24.png' },
            { name: ' 磨砂 ', value: 'imgs/cz25.png' },
            { name: ' 薄纱 ', value: 'imgs/cz26.png' },
            { name: ' 海绵 ', value: 'imgs/cz27.png' },
            { name: 'lace', value: 'imgs/cz28.png' },
            { name: ' 羊毛 ', value: 'imgs/cz29.png' },
            { name: ' 塑料 ', value: 'imgs/cz30.png' },
            { name: ' 石膏 ', value: 'imgs/cz31.png' },
            { name: ' 大理石 ', value: 'imgs/cz32.png' },
            { name: ' 陶瓷 ', value: 'imgs/cz33.png' },
            { name: ' 亚克力 ', value: 'imgs/cz34.png' },
            { name: ' 透明 ', value: 'imgs/cz35.png' },
            { name: ' 玻璃 ', value: 'imgs/cz36.png' },
            { name: ' 水泥 ', value: 'imgs/cz37.png' },
            { name: ' 石头 ', value: 'imgs/cz38.png' },
            { name: ' 砖块 ', value: 'imgs/cz39.png' },
            { name: ' 混凝土 ', value: 'imgs/cz40.png' },
            { name: ' 金属 ', value: 'imgs/cz41.png' },
            { name: ' 沥青 ', value: 'imgs/cz42.png' }
        ]
    }
];


const picStyle = [
    {
        name: '画风',
        child: [
            { value: 'hf/1.png', name: 'Moebius (Jean Giraud)风格，极繁主义，极致表现力，浪漫感，细节完美，大师杰作。 创作一幅清新治愈的插画，全副翠绿色调 有二三只白色的小生物，圆滚滚的身体座在椅子上。 奇幻森林童话插画，展现一座依附于巨树、被藤蔓与绿植覆盖的树屋小酒馆，木质平台上摆放着桌椅与餐具，暖黄灯光从屋内与吊灯透出，背景是深邃的森林，整体氛围神秘、温馨且充满魔法感 。' },
            { value: 'hf/2.png', name: 'Moebius ( Jean Giraud ）风格，极繁主义，极致表现力，浪漫感，细节完美，大师杰作。森林秘境，神秘夏天，画面干净，色彩丰富。画面中心是清晨，阳光透过茂密的森林枝叶，洒在一片开满野花的草地上。草地上有一只大白精灵，它圆滚滚的身体侧卧着，白色的绒毛在阳光中泛着微光。周围是翠绿的草丛和五彩斑斓的野花，不远处有一条蜿蜒的小溪，溪水潺潺流淌。，整体画面运用明亮鲜艳的绿色为主色调，营造出一种奇幻、可爱且温馨的森林童话氛围，仿佛带领观众进入一个充满惊喜的童话世界。c4d渲染，皮克斯动漫效果，虚幻引擎渲染' },
            { value: 'hf/3.png', name: '手绘水彩风格，画面呈现精致的花园小景。白色纸张，黑色线条勾勒植物、石阶，搭配水彩上色（绿、白、橙等），丰富的植物，石阶蔓延，留白，营造出文艺、清新的氛围，尽显手工绘画的细腻与自然美好。' },
            { value: 'hf/4.png', name: '星际穿越，黑洞，黑洞里冲出一辆快支离破碎的复古列车，抢视觉冲击力，电影大片，末日既视感，动感，C4D，3D建模，对比色，oc渲染，光线追踪，动态模糊，景深，超现实主义，深蓝，画面通过细腻的丰富的色彩层次塑造主体与场景，质感真实，暗黑风背景的光影效果营造出氛围，整体兼具艺术幻想感，夸张的广角透视效果，耀光，反射，极致的光影，强引力，吞噬' },
            { value: 'hf/5.png', name: '画面整体以蓝、金为主色调，线稿呈现出鲜明的科技风格巧妙融合敦煌的建筑和敦煌飞天与流动云气元素而碰撞出古典与科幻交织的独特视觉效果。' },
            { value: 'hf/6.png', name: '帮我生成图片：粗略东方主义铅笔素描，‌布拉德·皮特肖像画，大师级别作品，顶级素描，专业构图，立体感，牛皮纸上的画作。图片风格为炭笔涂鸦。 。图片风格为水墨，比例 9:16。比例 9:16。' },
            { value: 'hf/7.png', name: '逼真的暗黑系场景中，1:7比例商业化绿巨人浩克模型呈单腿蹲造型置于电脑桌上，人物高精度建模，皮肤纹理与战衣细节清晰可见，底座为圆形透明亚克力材质，电脑屏幕显示该人物的3D建模线框过程图，屏幕旁摆放BANDAI风格玩具包装盒，盒面印有绿巨人浩克原始艺术插画，写实风格，特写，暗黑美学，低光照' },
            { value: 'hf/8.png', name: '一个以纯黑为背景的画面，采用侧面构图，展现戴棒球帽的微卷短发女生的剪影轮廓。姿态安静，画质细腻，呈现出高对比度的效果。色彩上只有黑色与被光线照亮的蓝色调剪影部分。风格偏向于艺术感与神秘感兼具。光线从侧前方打过来，春野樱微微发光，形成鲜明的明暗对比，塑造出立体的轮廓。 镜头与画面主体保持一定距离，以平视角度捕捉主体剪影，呈现出一种沉静且引人遐想的视觉感受。' },
            { value: 'hf/9.png', name: '真实照片，肌理感，黑神话风格，艺术氛围感加强 大写意，黑暗，采用非传统的构图方式，打破常规，阴森恐怖，诡异的古代灯火通明的庄园，红灯笼' },
        ]
    }
]

const keysWord = [
    {
        name: '常用',
        child: [
            {
                name: "优化 Tag",
                child: [
                    { word: "masterpiece 大师作品" },
                    { word: "best quality 最好画质" },
                    { word: "masterpiece,best quality,official art,extremely detailed CG unity 8k wallpaper 更高质量" }
                ]
            },
            {
                name: "其他 Tag",
                child: [
                    { word: "wedding dress:china dress:0.3 旗袍婚纱" },
                    { word: "arms behind head 双手脑后" },
                    { word: "arms up, armpits 举手露腋" },
                    { word: "tiamat (fate) 提亚马特" }
                ]
            }
        ]
    }, {
        name: '环境',
        child: [
            {
                name: "朝朝暮暮",
                child: [
                    { word: "day 白天" },
                    { word: "dusk 黄昏" },
                    { word: "night 夜晚" },
                    { word: "in spring 春" },
                    { word: "in summer 夏" },
                    { word: "in autumn 秋" },
                    { word: "in winter 冬" }
                ]
            },
            {
                name: "日月星辰",
                child: [
                    { word: "sun 太阳" },
                    { word: "sunset 落日" },
                    { word: "moon 月亮" },
                    { word: "full_moon 满月" },
                    { word: "stars 星星" },
                    { word: "cloudy 多云" },
                    { word: "rain 下雨" },
                    { word: "in the rain 雨中" },
                    { word: "rainy days 雨天" }
                ]
            },
            {
                name: "天涯海角",
                child: [
                    { word: "sky 天空" },
                    { word: "sea 大海" },
                    { word: "mountain 山" },
                    { word: "on a hill 山上" },
                    { word: "the top of the hill 山顶" },
                    { word: "in a meadow 草地" },
                    { word: "plateau 高原" },
                    { word: "on a desert 沙漠" },
                    { word: "in hawaii 夏威夷" },
                    { word: "cityscape 城市风景" },
                    { word: "landscape 风景" },
                    { word: "beautiful detailed sky 好天" },
                    { word: "beautiful detailed water 好水" },
                    { word: "on the beach 海滩上" },
                    { word: "on the ocean 在大海上" },
                    { word: "over the sea 海边上" },
                    { word: "beautiful purple sunset at beach" },
                    { word: "in the ocean 海边日落" },
                    { word: "against backlight at dusk 傍晚背对阳光" },
                    { word: "golden hour lighting 黄金时段照明" },
                    { word: "strong rim light 强边缘光" },
                    { word: "intense shadows 强阴影" },
                    { word: "fireworks 焰火" },
                    { word: "flower field 花田" },
                    { word: "underwater 水下" },
                    { word: "explosion 爆炸" },
                    { word: "in the cyberpunk city 在赛博朋克城市" },
                    { word: "steam 蒸汽" }
                ]
            }
        ]
    }, {
        name: '风格',
        child: [
            {
                name: "风格",
                child: [
                    { word: "artbook 原画" },
                    { word: "game_cg 游戏 CG" },
                    { word: "comic 漫画" },
                    { word: "4koma 四格" },
                    { word: "animated_gifgif 格式图片" },
                    { word: "dakimakura 抱枕" },
                    { word: "cosplay 角色扮演" },
                    { word: "crossover 穿越" },
                    { word: "guro 猎奇" },
                    { word: "realistic 写实" },
                    { word: "photo 照片" },
                    { word: "real 真实" },
                    { word: "landscape/scenery 风景" },
                    { word: "cityscape 城市风景" },
                    { word: "science_fiction 科技幻想" },
                    { word: "original 原创" },
                    { word: "parody 拙劣的模仿" },
                    { word: "personification 拟人" },
                    { word: "checkered 格子的" },
                    { word: "lowres 低分辨率" },
                    { word: "highres 高分辨率" },
                    { word: "absurdres 超高分辨率" },
                    { word: "incredibly_absurdres 极高分辨率" },
                    { word: "huge_filesize 超级高分辨率 / 大文件" },
                    { word: "wallpaper 壁纸" },
                    { word: "pixel_art 点阵图" },
                    { word: "monochrome 单色图片" },
                    { word: "colorful 色彩斑斓的" },
                    { word: "optical_illusion 视觉错误" },
                    { word: "fine_art_parody 名画模仿" },
                    { word: "sketch 素描" },
                    { word: "traditional_media 传统媒体（基本上是手绘稿）" },
                    { word: "watercolor_(medium) 透明水彩绘" },
                    { word: "silhouette 剪影" },
                    { word: "covr 封面" },
                    { word: "album 专辑" },
                    { word: "sample 图上有 sample 字样" },
                    { word: "back 背影像" },
                    { word: "bust 半身像" },
                    { word: "profile 侧面绘" },
                    { word: "expressions 表情绘（各种表情）" },
                    { word: "everyone 一部作品中的主要人物集齐" },
                    { word: "column_lineup 一列列小图组成大图" },
                    { word: "transparent_background 透明的背景 (.png)" },
                    { word: "simple_background 简单的背景 (无背景)" },
                    { word: "gradient_background 渐变的背景" },
                    { word: "zoom_layer 背景是前景的放大版" },
                    { word: "English 英文" },
                    { word: "Chinese 中文" },
                    { word: "French 法文" },
                    { word: "Japanese 日本人" },
                    { word: "translation_request 翻译" },
                    { word: "bad_idID 转向错误 (原地址或已被删除)" },
                    { word: "tagme 图片有一些上传者未知的项目" },
                    { word: "artist_request 作者未知，需要补完" },
                    { word: "what 不知所谓" },
                    { word: "dark 暗的" },
                    { word: "light 亮的" },
                    { word: "night 晚上" }
                ]
            }
        ]
    }, {
        name: '人物角色',
        child: [
            {
                name: "人物",
                child: [
                    { word: "girl 女孩" },
                    { word: "2girls2 女孩" },
                    { word: "3girls3 女孩" },
                    { word: "boy 男孩" },
                    { word: "2boys2 男孩" },
                    { word: "3boys3 男孩" },
                    { word: "solo 单人" },
                    { word: "multiple girls 多个" },
                    { word: "little girl 小女孩" },
                    { word: "little boy 小男孩" },
                    { word: "shota 正太" },
                    { word: "loli 萝莉" },
                    { word: "kawaii 可爱" },
                    { word: "mesugaki 雌小鬼" },
                    { word: "adorable girl 可爱的女孩" },
                    { word: "bishoujo 美少女" },
                    { word: "gyaru 辣妹" },
                    { word: "sisters 姐妹" },
                    { word: "ojousama 大小姐" },
                    { word: "mature female 成熟女性" },
                    { word: "mature 成熟" },
                    { word: "female pervert 痴女" },
                    { word: "milf 熟女" },
                    { word: "harem 后宫" }
                ]
            },
            {
                name: "角色",
                child: [
                    { word: "angel 天使" },
                    { word: "cheerleader 啦啦队" },
                    { word: "chibiQ 版人物" },
                    { word: "crossdressing 伪娘" },
                    { word: "devil 魔鬼" },
                    { word: "doll 人偶" },
                    { word: "elf 妖精" },
                    { word: "fairy 小精灵" },
                    { word: "female 女人" },
                    { word: "furry 兽人" },
                    { word: "orc 半兽人" },
                    { word: "giantess 女巨人" },
                    { word: "harem 后宫" },
                    { word: "idol 偶像" },
                    { word: "kemonomimi_mode 兽耳萝莉模式" },
                    { word: "loli 萝莉" },
                    { word: "magical_girl 魔法少女" },
                    { word: "maid 女仆" },
                    { word: "male 男人" },
                    { word: "mermaid 美人鱼" },
                    { word: "miko 巫女" },
                    { word: "milf 熟女" },
                    { word: "minigirl 迷你女孩" },
                    { word: "monster 怪物" },
                    { word: "multiple_girls 魔幻少女" },
                    { word: "ninja 忍者" },
                    { word: "no_humans 非人" },
                    { word: "nun 修女" },
                    { word: "nurse 护士" },
                    { word: "shota 正太" },
                    { word: "stewardess 空姐" },
                    { word: "student 学生" },
                    { word: "trap 伪娘" },
                    { word: "vampire 吸血鬼" },
                    { word: "waitress 女服务员" },
                    { word: "witch 女巫" },
                    { word: "yaoi 搞基" },
                    { word: "yukkuri_shiteitte_ne 油库里" },
                    { word: "yuri 百合" }
                ]
            }
        ]
    }, {
        name: '头发发饰',
        child: [
            {
                name: "长度",
                child: [
                    { word: "very short hair 很短" },
                    { word: "short hair 短发" },
                    { word: "medium hair 中发" },
                    { word: "long hair 长发" },
                    { word: "very long hair 很长" },
                    { word: "absurdly long hair 特别长" },
                    { word: "hair over shoulder 头发过肩" },
                    { word: "alternate hair length 有长有短" }
                ]
            },
            {
                name: "颜色",
                child: [
                    { word: "blonde hair 金色" },
                    { word: "brown hair 棕色" },
                    { word: "black hair 黑色" },
                    { word: "blue hair 蓝色" },
                    { word: "purple hair 紫色" },
                    { word: "pink hair 粉红" },
                    { word: "white hair 白色" },
                    { word: "red hair 红色" },
                    { word: "grey hair 灰色" },
                    { word: "green hair 绿色" },
                    { word: "silver hair 银色" },
                    { word: "orange hair 橙色" },
                    { word: "light brown hair 浅棕" },
                    { word: "light purple hair 浅紫" },
                    { word: "light blue hair 浅蓝" },
                    { word: "platinum blonde hair 铂金色" },
                    { word: "gradient hair 渐变" },
                    { word: "multicolored hair 多色" },
                    { word: "shiny hair 闪亮" },
                    { word: "two-tone hair 双色" },
                    { word: "streaked hair 挑染" },
                    { word: "aqua hair 水色" },
                    { word: "colored inner hair 内层彩发" },
                    { word: "alternate hair color 交替发色" },
                    { word: "hair up 头发起来" },
                    { word: "hair down 头发下垂" },
                    { word: "wet hair 湿头发" }
                ]
            },
            {
                name: "发型",
                child: [
                    { word: "ahoge 呆毛" },
                    { word: "antenna hair 多根呆毛" },
                    { word: "bob cut 妹妹切" },
                    { word: "hime_cut 公主切" },
                    { word: "crossed bangs 交叉刘海" },
                    { word: "hair wings 翼状头发" },
                    { word: "disheveled hair 蓬发" },
                    { word: "wavy hair 波浪头" },
                    { word: "curly_hair 卷发" },
                    { word: "hair in takes 收拢" },
                    { word: "forehead 露额头" },
                    { word: "drill hair 公主卷" },
                    { word: "hair bun 包子头" },
                    { word: "double_bun 俩包子头" },
                    { word: "straight hair 直发" },
                    { word: "spiked hair 尖刺的头发" },
                    { word: "short hair with long locks 短发长鬓角" },
                    { word: "low-tied long hair 低扎长发" },
                    { word: "asymmetrical hair 不对称的头发" },
                    { word: "alternate hairstyle 交替发型" },
                    { word: "big hair 大头发" },
                    { word: "hair strand 发丝" },
                    { word: "hair twirling 卷发" },
                    { word: "pointy hair 尖头头发" },
                    { word: "hair slicked back 头发向后梳" },
                    { word: "hair pulled back 头发向后拉" },
                    { word: "split-color hair 分色头发" }
                ]
            }, {
                name: "辫子",
                child: [
                    { word: "braid 辫子" },
                    { word: "twin braids 双辫子" },
                    { word: "single braid 单辫" },
                    { word: "side braid 侧辫子" },
                    { word: "long braid 长辫子" },
                    { word: "french braid 法式辫子" },
                    { word: "crown braid 皇冠编织" },
                    { word: "braided bun 编织发髻" },
                    { word: "ponytail 马尾辫" },
                    { word: "braided ponytail 编马尾" },
                    { word: "high ponytail 高马尾" },
                    { word: "twintails 双马尾" },
                    { word: "short_ponytail 短马尾" },
                    { word: "twin_braids 双辫子" },
                    { word: "Side ponytail 侧马" }
                ]
            },
            {
                name: "刘海 / 其他",
                child: [
                    { word: "bangs 刘海" },
                    { word: "blunt bangs 齐刘海" },
                    { word: "parted bangs 分刘海" },
                    { word: "swept bangs 侧扫刘海" },
                    { word: "crossed bangs 交叉刘海" },
                    { word: "asymmetrical bangs 不对称刘海" },
                    { word: "braided bangs 辫子刘海" },
                    { word: "long bangs 长刘海" },
                    { word: "bangs pinned back 往后夹" },
                    { word: "diagonal bangs 斜刘海" },
                    { word: "dyed bangs 染刘海" },
                    { word: "hair between eyes 眼睛之间的头发" },
                    { word: "hair over one eye 一只眼睛上的头发" },
                    { word: "hair over eyes 头发遮住眼睛" },
                    { word: "hair behind ear 耳朵后面的头发" },
                    { word: "hair between breasts 乳房之间的毛发" },
                    { word: "hair over breasts 乳房上的头发" },
                    { word: "hair censor 刘海 + 长发？" }
                ]
            }, {
                name: "发饰",
                child: [
                    { word: "hair ornament 发饰" },
                    { word: "hair bow 蝴蝶结" },
                    { word: "hair ribbon 发带" },
                    { word: "hairband 发带" },
                    { word: "hair flower 头花" },
                    { word: "hair bun 发髻" },
                    { word: "hair bobbles 毛球" },
                    { word: "hairclip 发夹" },
                    { word: "single hair bun 单发髻" },
                    { word: "x hair ornamentx 发饰" },
                    { word: "black hairband 黑色发带" },
                    { word: "hair scrunchie 发箍" },
                    { word: "hair rings 发圈" },
                    { word: "tied hair 扎头发" },
                    { word: "hairpin 发夹" },
                    { word: "white hairband 白色发带" },
                    { word: "hair tie 发带" },
                    { word: "frog hair ornament 青蛙发饰" },
                    { word: "food-themed hair ornament 食物发饰" },
                    { word: "tentacle hair 触手头发" },
                    { word: "star hair ornament 星星发饰" },
                    { word: "hair bell 发铃" },
                    { word: "heart hair ornament 心形发饰" },
                    { word: "red hairband 红色发带" },
                    { word: "butterfly hair ornament 蝴蝶发饰" },
                    { word: "hair stick 发棒" },
                    { word: "snake hair ornament 蛇发饰" },
                    { word: "lolita hairband 洛丽塔发带" },
                    { word: "crescent hair ornament 新月发饰" },
                    { word: "cone hair bun 锥形发髻" },
                    { word: "feather hair ornament 羽毛头饰" },
                    { word: "blue hairband 蓝色发带" },
                    { word: "anchor hair ornament 锚发饰" },
                    { word: "leaf hair ornament 叶发饰" },
                    { word: "bunny hair ornament 兔子头饰" },
                    { word: "skull hair ornament 骷髅头饰" },
                    { word: "yellow hairband 黄色发带" },
                    { word: "pink hairband 粉色发带" },
                    { word: "dark blue hair 深蓝色头发" },
                    { word: "bow hairband 蝴蝶结发带" },
                    { word: "cat hair ornament 猫头饰" },
                    { word: "musical note hair ornament 音符发饰" },
                    { word: "carrot hair ornament 胡萝卜发饰" },
                    { word: "purple hairband 紫色发带" },
                    { word: "hair tucking 头发掖" },
                    { word: "hair beads 发珠" },
                    { word: "multiple hair bows 多个蝴蝶结" },
                    { word: "hairpods 发夹" },
                    { word: "bat hair ornament 蝙蝠发饰" },
                    { word: "bone hair ornament 骨发饰" },
                    { word: "orange hairband 橙色发带" },
                    { word: "multi-tied hair 多扎头发" },
                    { word: "snowflake hair ornament 雪花发饰" }
                ]
            }
        ]
    }, {
        name: '五官表情',
        child: [
            {
                name: "表情相关",
                child: [
                    { word: "food on face 食物在脸上（食物可替换）" },
                    { word: "light blush 淡淡腮红" },
                    { word: "facepaint 面纹" },
                    { word: "makeup 浓妆" },
                    { word: "cute face 可爱表情" },
                    { word: "white colored eyelashes 白色睫毛" },
                    { word: "longeyelashes 长睫毛" },
                    { word: "white eyebrows 白色眉毛" },
                    { word: "tsurime 吊眼角" },
                    { word: "gradient_eyes 渐变眼" },
                    { word: "beautiful detailed eyes 美丽的细节眼睛" },
                    { word: "tareme 垂眼角" },
                    { word: "slit pupils 猫眼" },
                    { word: "heterochromia 异色瞳" },
                    { word: "heterochromia blue red 红蓝眼" },
                    { word: "aqua eyes 水汪汪大眼" },
                    { word: "looking at viewer 看你" },
                    { word: "eyeball 盯着看" },
                    { word: "stare 凝视" },
                    { word: "visible through hair 透过刘海看" },
                    { word: "looking to the side 看旁边" },
                    { word: "constricted pupils 收缩的瞳孔" },
                    { word: "symbol-shaped pupils 符号形状的瞳孔" },
                    { word: "heart in eye♥" },
                    { word: "heart-shaped pupils 爱心瞳孔" },
                    { word: "wink 眨眼" },
                    { word: "mole under eye 眼下痣" },
                    { word: "eyes closed 闭眼" },
                    { word: "no_nose 没鼻子" },
                    { word: "fake animal ears 动物耳朵" },
                    { word: "animal ear fluff 动物耳绒毛" },
                    { word: "animal_ears 动物耳朵" },
                    { word: "fox_ears 狐狸耳朵" },
                    { word: "bunny_ears 兔子耳朵" },
                    { word: "cat_ears 猫耳" },
                    { word: "dog_ears 狗耳" },
                    { word: "mouse_ears 叔耳" },
                    { word: "hair ear 头发上耳朵" },
                    { word: "pointy ears 尖耳" },
                    { word: "light smile 微笑" },
                    { word: "seductive smile 诱惑笑" },
                    { word: "grin 露齿而笑" },
                    { word: "laughing 笑" },
                    { word: "teeth 牙" },
                    { word: "excited 兴奋" },
                    { word: "embarrassed 害羞" },
                    { word: "blush 脸红" },
                    { word: "shy 害羞" },
                    { word: "nose blush 害羞" },
                    { word: "expressionless 无表情" },
                    { word: "expressionless eyes 失神" },
                    { word: "sleepy 困" },
                    { word: "drunk 喝醉的" },
                    { word: "tears 哭" },
                    { word: "crying with eyes open 哭" },
                    { word: "sad 悲伤的" },
                    { word: "pout 别扭 努嘴" },
                    { word: "sigh 叹气" },
                    { word: "wide eyed 睁大眼睛" },
                    { word: "angry 生气" },
                    { word: "annoyed 苦恼的" },
                    { word: "frown 皱眉" },
                    { word: "smirk 认真" },
                    { word: "serious 严肃" },
                    { word: "jitome 鄙夷" },
                    { word: "scowl 锐利" },
                    { word: "crazy 疯狂的" },
                    { word: "dark_persona 黑化的" },
                    { word: "smirk 微笑" },
                    { word: "smug 得意" },
                    { word: "naughty_face 调皮脸" },
                    { word: "one eye closed 一只眼睛闭上" },
                    { word: "half-closed eyes 半闭眼睛" },
                    { word: "nosebleed 鼻血" },
                    { word: "eyelid pull 做鬼脸" },
                    { word: "tongue 舌头" },
                    { word: "tongue out 吐舌" },
                    { word: "closed mouth 闭嘴" },
                    { word: "open mouth 张嘴" },
                    { word: "lipstick 口红" },
                    { word: "fangs 尖牙" },
                    { word: "clenched teeth 咬紧牙关" },
                    { word: ":3u 猫嘴" },
                    { word: ":p 向下吐舌头" },
                    { word: ":q 向上吐舌头" },
                    { word: ":t 不耐烦" },
                    { word: ":d 杯型笑脸" }
                ]
            }

        ]
    }, {
        name: '眼睛',
        child: [
            {
                name: "颜色",
                child: [
                    { word: "blue eyes 蓝色" },
                    { word: "red eyes 红色" },
                    { word: "brown eyes 棕色" },
                    { word: "green eyes 绿色" },
                    { word: "purple eyes 紫色" },
                    { word: "yellow eyes 黄色" },
                    { word: "pink eyes 粉红" },
                    { word: "black eyes 黑色" },
                    { word: "aqua eyes 水蓝色" },
                    { word: "orange eyes 橙色" },
                    { word: "grey eyes 灰色" },
                    { word: "multicolored eyes 五彩" },
                    { word: "white eyes 白色" },
                    { word: "gradient eyes 渐变" }
                ]
            },
            {
                name: "状态",
                child: [
                    { word: "closed eyes 闭上眼睛" },
                    { word: "half-closed eyes 半闭眼" },
                    { word: "crying with eyes open 睁着眼睛哭" },
                    { word: "narrowed eyes 眯起眼睛" },
                    { word: "hidden eyes 隐藏的眼睛" },
                    { word: "heart-shaped eyes 心形眼睛" },
                    { word: "button eyes 纽扣眼" },
                    { word: "cephalopod eyes 头足类眼睛" },
                    { word: "eyes visible through hair 透过头发看见眼睛" },
                    { word: "glowing eyes 发光的眼睛" },
                    { word: "empty eyes 空洞的眼睛" },
                    { word: "rolling eyes 翻白眼" },
                    { word: "blank eyes 空白的眼睛" },
                    { word: "no eyes 没有眼睛" },
                    { word: "sparkling eyes 闪闪发光的眼睛" },
                    { word: "extra eyes 额外的眼睛" },
                    { word: "crazy eyes 疯狂的眼睛" },
                    { word: "solid circle eyes 实心圆眼" },
                    { word: "solid oval eyes 实心椭圆形眼睛" },
                    { word: "uneven eyes 不均匀的眼睛" },
                    { word: "blood from eyes 眼睛里的血" }
                ]
            },
            {
                name: "其他",
                child: [
                    { word: "eyeshadow 眼影" },
                    { word: "red eyeshadow 红色眼影" },
                    { word: "blue eyeshadow 蓝色眼影" },
                    { word: "purple eyeshadow 紫色眼影" },
                    { word: "pink eyeshadow 粉色眼影" },
                    { word: "green eyeshadow 绿色眼影" },
                    { word: "bags under eyes 眼袋" },
                    { word: "ringed eyes 眼圈" },
                    { word: "covered eyes 蒙住眼睛" },
                    { word: "covering eyes 遮住眼睛" },
                    { word: "shading eyes 遮住眼睛" }
                ]
            }
        ]
    }, {
        name: '身体',
        child: [
            {
                name: "胸",
                child: [
                    { word: "breasts 胸" },
                    { word: "small breasts 小" },
                    { word: "medium breasts 中" },
                    { word: "large breasts 大" },
                    { word: "huge breasts 超大" },
                    { word: "alternate breast size 不同尺寸" },
                    { word: "mole on breast 乳房上有痣" },
                    { word: "between breasts 两胸之间" },
                    { word: "breasts apart 胸部分开" },
                    { word: "hanging breasts 晃来晃去" },
                    { word: "bouncing breasts 弹来弹去" }
                ]
            }
        ]
    }, {
        name: '服装',
        child: [
            {
                name: "衣服",
                child: [
                    { word: "sailor collar 领子" },
                    { word: "hat 帽子" },
                    { word: "shirt 衬衫" },
                    { word: "serafuku 水手服" },
                    { word: "sailor suite 水手服" },
                    { word: "sailor shirt 水手服" },
                    { word: "shorts under skirt 水手服" },
                    { word: "collared shirt 有领衬衣" },
                    { word: "school uniform 学校制服" },
                    { word: "seifuku 日本学生服" },
                    { word: "business_suit 职场制服" },
                    { word: "jacket 夹克" },
                    { word: "suit 西装" },
                    { word: "garreg mach monastery uniform 火焰纹章军服" },
                    { word: "revealing dress 礼服长裙" },
                    { word: "pink lucency full dress 礼服" },
                    { word: "cleavage dress 露出胸口部分的连衣裙" },
                    { word: "sleeveless dress 无袖连衣裙" },
                    { word: "whitedress 白色连衣裙" },
                    { word: "wedding_dress 婚纱" },
                    { word: "Sailor dress 水手连衣裙" },
                    { word: "sweater dress 毛衣裙" },
                    { word: "ribbed sweater 罗纹毛衣" },
                    { word: "sweater jacket 毛衣夹克" },
                    { word: "dungarees 工装服" },
                    { word: "brown cardigan 棕色开襟衫（外套）" },
                    { word: "hoodie 连帽衫，卫衣" },
                    { word: "robe 长袍" },
                    { word: "cape 斗篷" },
                    { word: "cardigan 羊毛衫" },
                    { word: "apron 围裙" },
                    { word: "gothic 哥特风格" },
                    { word: "lolita_fashion 洛丽塔风格" },
                    { word: "gothic_lolita 哥特洛丽塔风格" },
                    { word: "western 西部风格" },
                    { word: "tartan 格子花纹" },
                    { word: "off_shoulder 露单肩" },
                    { word: "bare_shoulders 露双肩" },
                    { word: "barefoot 赤脚" },
                    { word: "bare_legs 裸足" },
                    { word: "striped 横条花纹的" },
                    { word: "polka_dot 点状花纹的" },
                    { word: "frills 皱边的" },
                    { word: "lace 花边" },
                    { word: "buruma 日本女生运动短裤" },
                    { word: "sportswear 运动服" },
                    { word: "gym_uniform 运动服" },
                    { word: "tank_top 女用背心" },
                    { word: "cropped jacket 裁剪短夹克" },
                    { word: "black sports bra 运动胸罩" },
                    { word: "crop top 漏脐装" },
                    { word: "pajamas 睡衣" },
                    { word: "japanese_clothes 和服" },
                    { word: "obi 衣带 (和服用)" },
                    { word: "mesh 网眼上衣" },
                    { word: "sleeveless shirt 无袖上衣" },
                    { word: "detached_sleeves 袖肩分离装" },
                    { word: "white bloomers 白色灯笼裤" },
                    { word: "high - waist shorts 高腰短裤" },
                    { word: "pleated_skirt 百褶裙" },
                    { word: "skirt 裙子" },
                    { word: "miniskirt 迷你裙" },
                    { word: "short shorts 热裤" },
                    { word: "summer_dress 夏日长裙" },
                    { word: "bloomers 灯笼裤" },
                    { word: "shorts 短裤" },
                    { word: "bike_shorts 自行车短裤" },
                    { word: "dolphin shorts 海豚短裤" },
                    { word: "belt 腰带" },
                    { word: "bikini 比基尼（前加颜色）" },
                    { word: "sling bikini 吊索比基尼" },
                    { word: "bikini_top 比基尼乳罩" },
                    { word: "bikini top only 上身比基尼" },
                    { word: "side - tie bikini bottom 侧边系带比基尼下装" },
                    { word: "side-tie_bikini 系带式比基尼" },
                    { word: "friled bikini 褶边比基尼" },
                    { word: "bikini under clothes 比基尼内衣" },
                    { word: "swimsuit 泳装" },
                    { word: "school swimsuit 学校泳衣" },
                    { word: "one-piece swimsuit 连体泳衣" },
                    { word: "competition swimsuit 竞技泳衣" },
                    { word: "Sukumizu 死库水" }
                ]
            }
        ]
    }, {
        name: '袜子&腿饰',
        child: [
            {
                name: "袜子",
                child: [
                    { word: "bare legs 裸腿" },
                    { word: "garter straps 吊袜带" },
                    { word: "garter belt 吊袜带" },
                    { word: "socks 袜子" },
                    { word: "kneehighs 过膝袜" },
                    { word: "white kneehighs 白色过膝袜" },
                    { word: "black kneehighs 黑色过膝袜" },
                    { word: "over-kneehighs 过膝袜" },
                    { word: "single kneehigh 单只过膝袜" },
                    { word: "tabi 日式厚底短袜" },
                    { word: "bobby socks 短袜" },
                    { word: "loose socks 堆堆袜" },
                    { word: "single sock 单袜" },
                    { word: "no socks 没有袜子" },
                    { word: "socks removed 脱掉袜子" },
                    { word: "ankle socks 及踝袜" },
                    { word: "striped socks 条纹袜" },
                    { word: "blue socks 蓝袜子" },
                    { word: "grey socks 灰袜子" },
                    { word: "red socks 红袜子" },
                    { word: "frilled socks 荷叶边袜子" }
                ]
            },
            {
                name: "长筒袜",
                child: [
                    { word: "thighhighs 长筒袜" },
                    { word: "black thighhighs 黑色长筒袜" },
                    { word: "white thighhighs 白色长筒袜" },
                    { word: "striped thighhighs 条纹长筒袜" },
                    { word: "brown thighhighs 棕色长筒袜" },
                    { word: "blue thighhighs 蓝色长筒袜" },
                    { word: "red thighhighs 红色长筒袜" },
                    { word: "purple thighhighs 紫色长筒袜" },
                    { word: "pink thighhighs 粉色长筒袜" },
                    { word: "grey thighhighs 灰色长筒袜" },
                    { word: "thighhighs under boots 靴子长筒袜" },
                    { word: "green thighhighs 绿色长筒袜" },
                    { word: "yellow thighhighs 黄色长筒袜" },
                    { word: "orange thighhighs 橙色长筒袜" },
                    { word: "vertical-striped thighhighs 竖条纹长筒袜" },
                    { word: "frilled thighhighs 褶边长筒袜" },
                    { word: "fishnet thighhighs 渔网长筒袜" }
                ]
            },
            {
                name: "连裤袜",
                child: [
                    { word: "pantyhose 连裤袜" },
                    { word: "black pantyhose 黑色连裤袜" },
                    { word: "white pantyhose 白色连裤袜" },
                    { word: "thighband pantyhose 绑腿连裤袜" },
                    { word: "brown pantyhose 棕色连裤袜" },
                    { word: "fishnet pantyhose 渔网连裤袜" },
                    { word: "striped pantyhose 竖条纹连裤袜" },
                    { word: "vertical-striped pantyhose 竖条纹连裤袜" },
                    { word: "grey pantyhose 灰色连裤袜" },
                    { word: "blue pantyhose 蓝色连裤袜" },
                    { word: "single leg pantyhose 单腿连裤袜" },
                    { word: "purple pantyhose 紫色连裤袜" },
                    { word: "red pantyhose 红色连裤袜" },
                    { word: "fishnet legwear 渔网袜" }
                ]
            }, {
                name: "腿饰 & 组合",
                child: [
                    { word: "bandaged leg 包扎腿" },
                    { word: "bandaid on leg 腿上的绷带" },
                    { word: "mechanical legs 机械腿" },
                    { word: "leg belt 腿带" },
                    { word: "leg tattoo 腿部纹身" },
                    { word: "bound legs 绑腿" },
                    { word: "leg lock 腿锁" },
                    { word: "panties under pantyhose 连裤袜下的内裤" },
                    { word: "panty & stocking with garterbelt 吊带袜内裤和长袜" },
                    { word: "thighhighs over pantyhose 连裤袜加长筒袜" },
                    { word: "socks over thighhighs 长筒袜加短袜" },
                    { word: "panties over pantyhose 连裤袜上的内裤" },
                    { word: "pantyhose under swimsuit 泳衣下连裤袜" },
                    { word: "black garter belt 黑色吊袜带" },
                    { word: "neck garter 吊袜带" },
                    { word: "white garter straps 白色吊袜带" },
                    { word: "black garter straps 黑色吊袜带" },
                    { word: "ankle garter 脚踝吊袜带" }
                ]
            },
            {
                name: "裤袜",
                child: [
                    { word: "no legwear 裸腿" },
                    { word: "black legwear 黑色裤袜" },
                    { word: "white legwear 白色裤袜" },
                    { word: "tom legwear 撕裂的裤袜" },
                    { word: "striped legwear 条纹裤袜" },
                    { word: "asymmetrical legwear 不对称裤腿" },
                    { word: "brown legwear 棕色裤袜" },
                    { word: "uneven legwear 不均匀的裤腿" },
                    { word: "toeless legwear 无趾裤袜" },
                    { word: "print legwear 印花裤袜" },
                    { word: "lace-trimmed legwear 蕾丝边裤袜" },
                    { word: "red legwear 红色裤袜" },
                    { word: "mismatched legwear 不匹配的腿饰" },
                    { word: "legwear under shorts 短裤下的裤袜" },
                    { word: "purple legwear 紫色裤袜" },
                    { word: "grey legwear 灰色裤袜" },
                    { word: "blue legwear 蓝色裤袜" },
                    { word: "pink legwear 粉色裤袜" },
                    { word: "aigyle legwear 菱形裤腿" },
                    { word: "ribbon-trimmed legwear 丝带边饰裤袜" },
                    { word: "american flag legwear 星条旗裤袜" },
                    { word: "green legwear 绿色裤袜" },
                    { word: "vertical-striped legwear 竖条纹裤袜" },
                    { word: "frilled legwear 褶边裤袜" },
                    { word: "stirrup legwear 马镫裤" },
                    { word: "alternate legwear 备用裤袜" },
                    { word: "seamed legwear 接缝裤袜" },
                    { word: "yellow legwear 黄色裤袜" },
                    { word: "multicolored legwear 五彩裤袜" },
                    { word: "ribbed legwear 罗纹裤袜" },
                    { word: "fur-trimmed legwear 毛皮裤袜" },
                    { word: "see-through legwear 透视裤袜" },
                    { word: "legwear garter 裤袜吊袜带" },
                    { word: "two-tone legwear 双色裤袜" },
                    { word: "latex legwear 乳胶裤袜" }
                ]
            }
        ]
    }, {
        name: '鞋子',
        child: [
            {
                name: "鞋子",
                child: [
                    { word: "shoes 鞋子" },
                    { word: "boots 靴子" },
                    { word: "loafers 乐福鞋" },
                    { word: "high heels 高跟鞋" },
                    { word: "cross-laced_footwear 系带靴" },
                    { word: "mary_janes 玛丽珍鞋" },
                    { word: "uwabaki 女式学生鞋" },
                    { word: "slippers 拖鞋" },
                    { word: "knee_boots 马靴" }
                ]
            }
        ]
    }, {
        name: '装饰',
        child: [
            {
                name: "装饰",
                child: [
                    { word: "halo 光环" },
                    { word: "mini_top_hat 迷你礼帽" },
                    { word: "beret 贝雷帽" },
                    { word: "hood 兜帽" },
                    { word: "nurse cap 护士帽" },
                    { word: "tiara 皇冠" },
                    { word: "oni horns 鬼角" },
                    { word: "demon horns 恶魔角" },
                    { word: "hair ribbon 发带" },
                    { word: "flower ribbon 花丝带" },
                    { word: "hairband 发卡" },
                    { word: "hairclip 发夹" },
                    { word: "hair_ribbon 发带" },
                    { word: "hair_flower 发花" },
                    { word: "hair_ornament 头饰" },
                    { word: "bowtie 蝴蝶结" },
                    { word: "hair_bow 蝴蝶结发饰" },
                    { word: "maid_headress 女仆头饰" },
                    { word: "bow 服装饰品 / 头部饰品" },
                    { word: "hair ornament 发饰" },
                    { word: "heart hair ornament 心形" },
                    { word: "bandaid hair ornament 创可贴" },
                    { word: "hair bun 发包" },
                    { word: "cone hair bun 锥形发髻" },
                    { word: "double bun 双发髻" },
                    { word: "semi-rimless eyewear 半无框的眼镜" },
                    { word: "sunglasses 太阳镜" },
                    { word: "goggles 风镜" },
                    { word: "eyepatch 眼罩 (独眼)" },
                    { word: "black blindfold 黑色眼罩" },
                    { word: "headphones 耳机" },
                    { word: "veil 面纱" },
                    { word: "mouth mask 口罩" },
                    { word: "glasses 眼镜" },
                    { word: "earrings 耳环" },
                    { word: "jewelry 首饰" },
                    { word: "bell 铃铛" },
                    { word: "ribbon_choker 颈带" },
                    { word: "black choker 颈部饰品" },
                    { word: "necklace 项链" },
                    { word: "headphones around neck 耳机套脖子上" },
                    { word: "collar 项圈" },
                    { word: "sailor_collar 水手领" },
                    { word: "neckerchief 领巾" },
                    { word: "necktie 领带" },
                    { word: "cross necklace 十字架" },
                    { word: "pendant 吊坠" },
                    { word: "jewelry 珠宝" },
                    { word: "scarf 围巾" },
                    { word: "armband 臂章" },
                    { word: "armlet 臂环" },
                    { word: "arm strap 臂带" },
                    { word: "elbow gloves 肘部手套" },
                    { word: "half gloves 露指手套" },
                    { word: "fingerless_gloves 手镯" },
                    { word: "gloves 手套" },
                    { word: "fingerless gloves 五指手套" },
                    { word: "chains 锁链" },
                    { word: "shackles 手链" },
                    { word: "cuffs 手铐" },
                    { word: "handcuffs 手铐" },
                    { word: "bracelet 手镯" },
                    { word: "wristwatch 手表" },
                    { word: "wristband 腕带" },
                    { word: "wrist_cuffs 腕饰" },
                    { word: "holding book 拿着书" },
                    { word: "holding sword 拿着剑" },
                    { word: "tennis racket 球拍" },
                    { word: "cane 手杖" },
                    { word: "backpack 双肩包" },
                    { word: "school bag 书包" },
                    { word: "satchel 肩背书包" },
                    { word: "smartphone 手机" },
                    { word: "bandaid 创可贴" }
                ]
            }
        ]
    }, {
        name: '动作',
        child: [
            {
                name: "动作",
                child: [
                    { word: "head tilt 歪头" },
                    { word: "turning around 回头" },
                    { word: "looking back 回头" },
                    { word: "looking down 向下看" },
                    { word: "looking up 向上看" },
                    { word: "smelling 闻" },
                    { word: "hand to_mouth 手放在嘴边" },
                    { word: "arm at side 手放头旁边" },
                    { word: "arms behind head 手放脑后" },
                    { word: "arms behind back 手放后面" },
                    { word: "hand on own chest 手放在自己的胸前" },
                    { word: "arms_crossed 手交叉于胸前" },
                    { word: "hand on hip 手放臀" },
                    { word: "hand on another's hip 手放臀" },
                    { word: "hand_on_hip 单手插腰" },
                    { word: "hands_on_hips 双手叉腰" },
                    { word: "arms up 举手" },
                    { word: "hands up 举手" },
                    { word: "stretch 伸懒腰" },
                    { word: "amputee 手盖脸" },
                    { word: "leg hold 手把腿抓着" },
                    { word: "grabbing 抓住" },
                    { word: "holding 拿着" },
                    { word: "fingersmile 用手指做出来笑脸" },
                    { word: "hair_pull 拉头发" },
                    { word: "hair scrunchie 头发" },
                    { word: "w 手势" },
                    { word: "V 耶" },
                    { word: "peace symbol 耶" },
                    { word: "thumbs_up 翘大拇指" },
                    { word: "middle_finger 比出中指" },
                    { word: "Cat_Pose 猫爪手势" },
                    { word: "finger_gun 手枪手势" },
                    { word: "shushing 嘘手势" },
                    { word: "waving 招手" },
                    { word: "salute 敬礼" },
                    { word: "spread_arms 张手" },
                    { word: "spread_legs 张开腿" },
                    { word: "crossed_legs 二郎腿" },
                    { word: "fetal_position 曲腿至胸" },
                    { word: "leg_lift 抬一只脚" },
                    { word: "legs_up 抬两只脚" },
                    { word: "leaning forward 前倾" },
                    { word: "fetal position 婴儿姿势" },
                    { word: "against wall 靠着墙" },
                    { word: "on_stomach 趴着" },
                    { word: "squatting 蹲下" },
                    { word: "lying 躺着" },
                    { word: "sitting 坐" },
                    { word: "sitting on 坐" },
                    { word: "seiza 正坐" },
                    { word: "wanzaiw-sitting 割坐" },
                    { word: "Yokozuwari 侧身坐" },
                    { word: "indian_style 盘腿" },
                    { word: "leg_hug 抱腿" },
                    { word: "walking 走" },
                    { word: "running 跑" },
                    { word: "straddle 跨坐" },
                    { word: "straddling 跨坐" },
                    { word: "kneeling 下跪" },
                    { word: "smoking 抽烟" },
                    { word: "arm_Support 用手支撑住" },
                    { word: "caramelldansenicon" },
                    { word: "princess_carry 公主抱" },
                    { word: "fighting_stance 战斗姿态" },
                    { word: "upside-down 颠倒的" },
                    { word: "top-down_bottom-up 倒置 / 着臀部" },
                    { word: "bent_over 翘臀姿势" },
                    { word: "arched_back 弓身体" },
                    { word: "back-to-back 背对背" },
                    { word: "symmetrical_hand_pose 对手手" },
                    { word: "eye_contact 眼对眼（对视）" },
                    { word: "hug 拥抱" },
                    { word: "lap_pillow 膝枕" },
                    { word: "sleeping 睡觉" },
                    { word: "bathing 洗澡" },
                    { word: "mimikakik 掏耳勺" },
                    { word: "holding_hands 牵牵手" }
                ]

            },
            {
                name: "头发相关",
                child: [
                    { word: "hair blowing 吹头发" },
                    { word: "adjusting hair 调整头发" },
                    { word: "hand in own hair 手牵自己的头发" },
                    { word: "holding hair 握头发" },
                    { word: "tying hair 扎头发" },
                    { word: "grabbing another's hair 抓别人的头发" },
                    { word: "hands in hair 手在头发" },
                    { word: "brushing hair 梳头" },
                    { word: "washing hair 洗头" }
                ]
            }
        ]
    }
]